### ISSUE TITLE
tweak the html template to not display header image on post but on twitter card

### ISSUE THREAD

**Issue by emdelponte** [openplantpathology/OpenPlantPathology#34]
I will work on this

**Comment by emdelponte** [comment]
Uploaded the fix but it does not work

**Comment by adamhsparks** [comment]
I've pushed changes to fix the map but they aren't working either.

Something wrong with Netlify?

**Comment by adamhsparks** [comment]
It is responding very slowly.

**Comment by emdelponte** [comment]
I cleared cache and it is not slow. The map is still wrong though.

**Comment by emdelponte** [comment]
the map is fine offline, but does not update.

**Comment by adamhsparks** [comment]
Looks fine to me online now?

**Comment by emdelponte** [comment]
neat! working nicely.

**Comment by adamhsparks** [comment]
Something was wrong with Netlify. I had issues even accessing https://www.netlify.com/ earlier to for a new deployment and my PRs weren't showing me the preview deployment to check before merging.

**Comment by adamhsparks** [comment]
Don't know if you've seen this? Found it looking for other stuff this afternoon.

https://github.com/rstudio/blogdown/blob/master/docs/02-hugo.Rmd#shortcode

**Comment by emdelponte** [comment]
Academic Hugo theme has this feature by standard. We need to a create a header image for the post. However, in my tests the img did not appear on twitter.
